import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { motion } from "framer-motion";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#f8fafc] dark:bg-[#0f172a] py-12 px-4">
      <div className="container max-w-4xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <Card className="border-[#e2e8f0] dark:border-[#334155]">
            <CardHeader>
              <CardTitle className="text-3xl font-bold">Terms of Service</CardTitle>
              <p className="text-[#475569] dark:text-[#94a3b8]">Last updated: March 26, 2026</p>
            </CardHeader>
            <CardContent className="space-y-6">
              <div>
                <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
                <p className="text-[#475569] dark:text-[#94a3b8]">
                  By using Scanvas, you agree to these Terms of Service. If you do not agree, please do not use our service.
                </p>
              </div>
              
              <div>
                <h2 className="text-xl font-semibold mb-3">2. Service Usage</h2>
                <p className="text-[#475569] dark:text-[#94a3b8]">
                  Scanvas provides website accessibility auditing tools. You may use our service to scan websites you own or have permission to test. You are responsible for any websites you submit for analysis.
                </p>
              </div>
              
              <div>
                <h2 className="text-xl font-semibold mb-3">3. Intellectual Property</h2>
                <p className="text-[#475569] dark:text-[#94a3b8]">
                  Scanvas and its content, features, and functionality are owned by Scanvas and are protected by copyright and other intellectual property laws.
                </p>
              </div>
              
              <div>
                <h2 className="text-xl font-semibold mb-3">4. Disclaimer</h2>
                <p className="text-[#475569] dark:text-[#94a3b8]">
                  Scanvas provides automated accessibility auditing tools. Results are generated by automated systems and should not be considered a complete accessibility assessment. We recommend consulting with accessibility professionals for comprehensive compliance.
                </p>
              </div>
              
              <div>
                <h2 className="text-xl font-semibold mb-3">5. Limitation of Liability</h2>
                <p className="text-[#475569] dark:text-[#94a3b8]">
                  Scanvas shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of our service.
                </p>
              </div>
              
              <div>
                <h2 className="text-xl font-semibold mb-3">6. Changes to Terms</h2>
                <p className="text-[#475569] dark:text-[#94a3b8]">
                  We may modify these Terms at any time. Continued use of Scanvas constitutes acceptance of the modified terms.
                </p>
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </div>
  );
}