import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { motion } from "framer-motion";
import { FileText, CheckCircle, AlertCircle, Scale, Shield, Mail, ExternalLink, BookOpen } from "lucide-react";

export default function TermsOfService() {
  const sections = [
    {
      icon: <CheckCircle className="w-5 h-5" />,
      title: "1. Acceptance of Terms",
      content: "By using Scanvas, you agree to these Terms of Service. If you do not agree, please do not use our service.",
      highlight: false
    },
    {
      icon: <ExternalLink className="w-5 h-5" />,
      title: "2. Service Usage",
      content: "Scanvas provides website accessibility auditing tools. You may use our service to scan websites you own or have permission to test. You are responsible for any websites you submit for analysis.",
      highlight: true
    },
    {
      icon: <Scale className="w-5 h-5" />,
      title: "3. Intellectual Property",
      content: "Scanvas and its content, features, and functionality are owned by Scanvas and are protected by copyright and other intellectual property laws.",
      highlight: false
    },
    {
      icon: <AlertCircle className="w-5 h-5" />,
      title: "4. Disclaimer",
      content: "Scanvas provides automated accessibility auditing tools. Results are generated by automated systems and should not be considered a complete accessibility assessment. We recommend consulting with accessibility professionals for comprehensive compliance.",
      highlight: true
    },
    {
      icon: <Shield className="w-5 h-5" />,
      title: "5. Limitation of Liability",
      content: "Scanvas shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of our service.",
      highlight: false
    },
    {
      icon: <BookOpen className="w-5 h-5" />,
      title: "6. Changes to Terms",
      content: "We may modify these Terms at any time. Continued use of Scanvas constitutes acceptance of the modified terms.",
      highlight: false
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#f5f7fa] to-[#eef2f6] py-12 md:py-20 px-4">
      <div className="container max-w-4xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          {/* Hero Badge */}
          <div className="text-center mb-8">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-gradient-to-r from-[#334155]/10 to-[#5b6e8c]/10 text-[#334155] text-sm font-medium mb-6 border border-[#e2e8f0] backdrop-blur-sm">
              <FileText className="w-4 h-4" />
              <span>Legal Agreement</span>
            </div>
          </div>

          <Card className="border-[#e2e8f0] shadow-xl bg-white/90 backdrop-blur-sm overflow-hidden">
            <CardHeader className="border-b border-[#e2e8f0] bg-gradient-to-r from-[#f8fafc] to-white pb-6">
              <div className="flex items-center gap-3 mb-2">
                <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-[#334155] to-[#5b6e8c] flex items-center justify-center shadow-md">
                  <FileText className="w-6 h-6 text-white" />
                </div>
                <div>
                  <CardTitle className="text-3xl md:text-4xl font-bold bg-gradient-to-r from-[#111827] to-[#334155] bg-clip-text text-transparent">
                    Terms of Service
                  </CardTitle>
                  <p className="text-[#64748b] mt-1">Last updated: March 26, 2026</p>
                </div>
              </div>
              <p className="text-[#475569] mt-4 pl-0 md:pl-16">
                These Terms of Service govern your use of Scanvas. Please read them carefully before using our service.
              </p>
            </CardHeader>
            
            <CardContent className="p-6 md:p-8 space-y-6">
              {sections.map((section, idx) => (
                <motion.div
                  key={idx}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: idx * 0.1 }}
                  className={`group ${section.highlight ? 'bg-[#334155]/5 rounded-lg p-4 -mx-1' : ''}`}
                >
                  <div className="flex gap-4">
                    <div className="flex-shrink-0">
                      <div className={`w-10 h-10 rounded-lg flex items-center justify-center transition-transform group-hover:scale-110 ${
                        section.highlight 
                          ? 'bg-gradient-to-br from-[#334155] to-[#5b6e8c] text-white shadow-md' 
                          : 'bg-gradient-to-br from-[#334155]/10 to-[#5b6e8c]/10 text-[#334155]'
                      }`}>
                        {section.icon}
                      </div>
                    </div>
                    <div className="flex-1">
                      <h2 className={`text-xl font-semibold mb-2 ${section.highlight ? 'text-[#111827]' : 'text-[#111827]'}`}>
                        {section.title}
                      </h2>
                      <p className="text-[#475569] leading-relaxed">
                        {section.content}
                      </p>
                    </div>
                  </div>
                  {idx < sections.length - 1 && (
                    <div className="border-b border-[#e2e8f0] my-6" />
                  )}
                </motion.div>
              ))}
            </CardContent>
          </Card>

          {/* Contact Section */}
          <div className="mt-8 text-center">
            <div className="inline-flex items-center gap-3 px-6 py-3 rounded-xl bg-white/80 backdrop-blur-sm border border-[#e2e8f0] shadow-sm">
              <Mail className="w-4 h-4 text-[#334155]" />
              <span className="text-sm text-[#475569]">Questions? Contact us at:</span>
              <a 
                href="mailto:legal@scanvas.com" 
                className="text-[#334155] font-medium hover:text-[#5b6e8c] transition-colors"
              >
                legal@scanvas.com
              </a>
            </div>
          </div>

          {/* Footer Note */}
          <div className="text-center mt-6">
            <p className="text-xs text-[#64748b]">
              By using Scanvas, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  );
}